export { default as Navbar } from './Navbar';
export { default as Hero } from './Hero';
export { default as Mobile } from './Mobile';
export { default as Dashboard } from './Dashboard';
export { default as SafetyComponent } from './SafetyComponent';
export { default as SupportComponent } from './SupportComponent';
export { default as Download } from './Download';
export { default as Blogs } from './Blogs';
export { default as Footer } from './Footer';
